### ISSUE TITLE
Can't find a way to assigned a custom plugin to a consumer

### ISSUE THREAD

**Issue by prouwens** [mybuilder/kongfig#104]
we have a custom plugin, that has to be applied and configure by customer.
Based on the documentation there is no way to do so.

**Comment by CyExy** [comment]
There is a way to register custom auth plugins with `--credential-schema`. If that isn't what you are after could you please provide more details about the plugin?

**Comment by prouwens** [comment]
hi,

Actually the plugin receive one parameter in the header and do some replacement. So it s not an actual authentication, more than a plugin that simply add something in the header, but as it s different by user I have to add it at consumer level.

**Comment by CyExy** [comment]
Sounds like an authentication plugin, even if it just add a header.

**Comment by CyExy** [comment]
This is an example of a [key auth](https://github.com/mybuilder/kongfig/blob/master/examples/key-auth.example.md). Aren't the curl calls similar to the ones done here for the auth plugin?

**Comment by prouwens** [comment]
this is the curl call : 
# Provisioning token for the created consumer
curl -i -X POST \
	--url http://localhost:8001/consumers/$1/myPlugin/ \
		--data "special_token=$3"

**Comment by CyExy** [comment]
config.yml

```yaml
consumers:
  - username: "the-user"
    ensure: "present"
    credentials:
      - name: "myPlugin"
        ensure: "present"
        attributes:
          special_token: "special key"
```

```bash
kongfig apply --path config.yml --credential-schema=myPlugin:special_token
```
