### ISSUE TITLE
anonymous_username is an unknown field

### ISSUE THREAD

**Issue by jameswestnz** [mybuilder/kongfig#108]
When running `kongfig apply`, I am getting the following error in the terminal:

```
PATCH http://kong:8001/plugins/463f37be-6f14-4891-a725-2ae6d81e384a
  { enabled: true,
   config: { anonymous_username: 'unauthorized' } }
 400 Bad Request { 'config.anonymous_username': 'anonymous_username is an unknown field' }
 Error: Bad Request
 {"config.anonymous_username":"anonymous_username is an unknown field"}
```

Excerpt from config file (plugins is global, not under an api):

```yaml
plugins: 
  - name: basic-auth
    attributes:
      enabled: true
      config:
        anonymous_username: unauthorized
```

It seems the `anonymous_username` property only works when a plugin is defined under an API. Is this intended? I was hoping to define an anonymous user at the global level - maybe I'm missing something?
