### ISSUE TITLE
Make `dump` output more easily diffable

### ISSUE THREAD

**Issue by janv8000** [mybuilder/kongfig#116]
The YAML output produced by a dump does not always retain the same order (between runs or between different instances).
## Output 1
```
host: <redacted>
https: true
headers:
  - 'X-APIKEY:...'
apis:
  - name: api1
    plugins:
      - name: second_plugin
        attributes:
          enabled: true
      - name: acl
        attributes:
          enabled: true
  - name: api2
    plugins:
      - name: acl
        attributes:
          enabled: true
```
## Output 2
```
host: <redacted>
https: true
headers:
  - 'X-APIKEY:...'
apis:
  - name: api2
    plugins:
      - name: acl
        attributes:
          enabled: true    
      - name: second_plugin
        attributes:
          enabled: true
  - name: api1
    plugins:
      - name: acl
        attributes:
          enabled: true
```

The two outputs are functionally equivalent but comparing them is a bit more work.

Ideally `api`'s would be ordered by name/id, then plugins by name/id, then ...
