### ISSUE TITLE
Kongfig apply is not  creating Basic-auth users

### ISSUE THREAD

**Issue by SSKasture** [mybuilder/kongfig#117]
This is my yml file

apis:
   - name: test
     ensure: present
     attributes: 
           upstream_url: "http://loacalhost:80/test"
           request_path: /test
           strip_request_path: true
     plugins:                  
            - name: acl
              attributes: 
                config:
                  whitelist: test_grp
            - name: rate-limiting
              attributes: 
                config:
                    minute : 3600
            - name: basic-auth
              attributes:
                config:
                  hide_credentials: false
consumers: 
    - username: testapi
      ensure: present
      acls: 
        - group: test_grp
          ensure: present
          credentials: 
            - name: "basic-auth"
              attributes: 
                  username: test1
                  password: JfhljBY9xspAfGZyQ6AKgmGx
            - name: "basic-auth"
              attributes: 
                  username: test2
                  password: 123
            - name: "basic-auth"
              attributes: 
                  username: test3
                  password: EG73k8lY3DJc5vAGhQpH6aWU 
            - name: "basic-auth"
              attributes: 
                  username: test4
                  password: ttwwdzkebmkdkbzdpvjp
            - name: "basic-auth"
              attributes: 
                  username: test5
                  password: cmYneZlsOMWuf9BKHMVWItVg
            - name: "basic-auth"
              attributes: 
                  username: test6
                  password: Hx996mmnEjVPVVkNGJBAlkh9  

It's not creating any of Test users in KONG
am I missing something?

Thank You
Sampada K.

**Comment by CyExy** [comment]
Hi it seems that you have `credentials` under `acls` group, and notice the test2 user password that should be a string

```yaml
apis:
   - name: test
     ensure: present
     attributes:
           upstream_url: "http://loacalhost:80/test"
           request_path: /test
           strip_request_path: true
     plugins:
            - name: acl
              attributes:
                config:
                  whitelist: test_grp
            - name: rate-limiting
              attributes:
                config:
                    minute : 3600
            - name: basic-auth
              attributes:
                config:
                  hide_credentials: false
consumers:
    - username: testapi
      ensure: present
      acls:
        - group: test_grp
          ensure: present
      credentials:
        - name: "basic-auth"
          attributes:
              username: test1
              password: JfhljBY9xspAfGZyQ6AKgmGx
        - name: "basic-auth"
          attributes:
              username: test2
              password: '123'
        - name: "basic-auth"
          attributes:
              username: test3
              password: EG73k8lY3DJc5vAGhQpH6aWU
        - name: "basic-auth"
          attributes:
              username: test4
              password: ttwwdzkebmkdkbzdpvjp
        - name: "basic-auth"
          attributes:
              username: test5
              password: cmYneZlsOMWuf9BKHMVWItVg
        - name: "basic-auth"
          attributes:
              username: test6
              password: Hx996mmnEjVPVVkNGJBAlkh9
```
