### ISSUE TITLE
Kongfig is not able at the moment to add 2 instances of the same plugin on the same API

### ISSUE THREAD

**Issue by JnMik** [mybuilder/kongfig#27]
First request-transformer plugin will POST, second will PATCH the previous one.

Example of a non-working yaml file

``` YAML
apis:
    -
      name: "some-api-name"
      attributes:
        request_path: "/some-path"
        upstream_url: "http://some-upstream-url.com"
      plugins:
        - # Config for everyone
          name: "request-transformer"
          attributes:
            config.replace.querystring: "param1:value1"
        - # Specific config for someone
          name: "request-transformer"
          consumer_id: "some-consumer-id"
          attributes:
            config.replace.querystring: "remote_api_key:123"
```

Kong is actually capable of handling multiple instances.

Code from plugin route (/apis/4015094e-7a5f-44c7-bd3b-ff5ba533bd0e/plugins)
http://screencast.com/t/zWwu1bKr3ax

Anyone else would need that feature ?
@CyExy Did you encountered this issue ? Have you planned to add this to the tool ? 

thx !

**Comment by CyExy** [comment]
@JnMik Does kong allow more than one `request-transformer` plugin per consumer?

**Comment by JnMik** [comment]
Yes, as you can see in my screencast link
(Did it with Postman)

**Comment by CyExy** [comment]
@JnMik The screenshot has one without consumer_id and one with.

**Comment by JnMik** [comment]
But they are both on the same API (which is my point).
I just wanted to show that kong allow it, but it's impossible to do with Kongfig.

**Comment by CyExy** [comment]
If it only allows one per consumer it would be easier to implement

**Comment by JnMik** [comment]
Well that would be a nice start I think

1 generic (consumer_id undefined)
and
1 per consumer (usually all configs per consumer should be in the same request-transformer)

**Comment by tophercullen** [comment]
@CyExy I believe #71 would fix this as well

**Comment by CyExy** [comment]
So possible now with using `username` in attributes that will be transformed to `consumer_id` when calling kong

```
apis:
    -
      name: "some-api-name"
      attributes:
        request_path: "/some-path"
        upstream_url: "http://some-upstream-url.com"
      plugins:
        - # Config for everyone
          name: "request-transformer"
          attributes:
            config.replace.querystring: "param1:value1"
        - # Specific config for someone
          name: "request-transformer"
          username: "some-consumer-username"
          attributes:
            config.replace.querystring: "remote_api_key:123"
```
