### ISSUE TITLE
Is there any way to encrypt basic-auth passwords in konfig configuration file?

### ISSUE THREAD

**Issue by uhashimi** [mybuilder/kongfig#35]
Currently, there seems to be no way to encrypt basic-auth passwords in Kongfig. It will be good to have this feature.

Something like following
```
consumers:
  - username: iphone-app
    credentials:
      - name: basic-auth
        attributes:
          username: # required
          password: #encryptedPassword
          encryptionMethod: SHA1

```
