### ISSUE TITLE
Kongfig doesn't permit custom credentials plugins

### ISSUE THREAD

**Issue by gudubeth** [mybuilder/kongfig#37]
I have a custom JWT credential plugin. When I try to run `kongfig apply` with this plugin configuration, it returns the error below:

    Error: Unknown credential "custom-jwt"

When I checked the code I saw that kongfig [checks if consumer credential is defined](https://github.com/mybuilder/kongfig/blob/master/src/core.js#L51) based on an [object named `consumerCredentialSchema`](https://github.com/mybuilder/kongfig/blob/master/src/core.js#L24). 

I think there should be a way to use custom credential plugins.

Example consumer config:

```yaml
consumers:
  - username: test
    custom_id: test
    credentials:
      - name: custom-jwt
        attributes:
          key: test
          algorithm: RS256
          rsa_public_key: longlonglongkey
```
