### ISSUE TITLE
Rate limiting plugin issue with multiple consumers

### ISSUE THREAD

**Issue by bmaynard** [mybuilder/kongfig#68]
I have multiple rate plugins assigned to a single api but each record is assigned to a different consumer.

When I do a dump it doesn't export the consumer id:

```
      - name: rate-limiting
        attributes:
          enabled: true
          config:
            minute: 300
            limit_by: ip
            fault_tolerant: true
            redis_database: 0
            redis_host: 127.0.0.1
            policy: redis
            redis_timeout: 2000
            redis_port: 6379
      - name: rate-limiting
        attributes:
          enabled: true
          config:
            limit_by: ip
            minute: 60
            fault_tolerant: true
            redis_database: 0
            redis_timeout: 2000
            policy: redis
            redis_host: 127.0.0.1
            redis_port: 6379
```

and if I add `consumer_id` to the attributes and run apply, it just updates the one plugin record and won't create a new record (if its a new plugin assigned to a different consumer).
