### ISSUE TITLE
Consumer information unavailable unless a consumer was managed

### ISSUE THREAD

**Issue by tophercullen** [mybuilder/kongfig#75]
I'm working on a PR that allows the usage of usernames or custom_ids when configuring plugins. The idea being to map them to the kong consumer_id in that environment.  

The problem I'm running into is that no consumer information is requested from the kong api (and thus available to other functions) unless there is a 'consumer' section in the config.  Example broken config

```
apis:
  - name: myapi
    ensure: "present" 
    attributes:
      upstream_url: https://service-api/ # (required)
      hosts: []
      uris: /myapi/
      methods: []
      strip_uri: false
      preserve_host: true
      retries: 5
      upstream_connect_timeout: 60000
      upstream_read_timeout: 60000
      upstream_send_timeout: 60000
      https_only: true 
      http_if_terminated: false
    plugins:
      - name: rate-limiting 
        ensure: "present" 
        username: user1
        attributes: 
          config:
            minute: 4
      - name: rate-limiting # kong plugin name
        ensure: "present" 
        custom_id: 1c6088ba-41f0-44be-9879-a784d8683788
        attributes:
          config:
            minute: 3
```

This results in "Error: Unable to find consumer user1". Debugging shows there is no consumer information available. Adding any consumer config (example below) results in consumer information being available, and the code works

```
consumers:
  - username: fakeuser
    ensure: "removed"
```

This is very likely not a bug, but a nuance of javascript I simply don't understand. I'd be very appreciative if you could point me in the right direction.
