### ISSUE TITLE
Kong v0.8.0 - error with pagination, wrong URL returned by Kong

### ISSUE THREAD

**Issue by vl4d** [mybuilder/kongfig#90]
Good Day, My current Kong version is 0.8.0 I am about to upgrade to 0.10 which is why I am running the kongfig (first time in over 7 months)

My kong has about 124 plugins being returned by` /plugins` route. 
I had done the pagination bit before, but it looks like kong returns a default kong url in the `json.next`. 

I get the error:

![screen shot 2017-08-17 at 17 56 44](https://user-images.githubusercontent.com/9806813/29424042-fb67fde4-8375-11e7-86d7-4c4a9dda23e2.png)

As can be seen though we pass the proper uri initially, the "json.next" returned from kong looks to be a default host and port thus throwing the error in red. 

I am willing to fix it, just want to make sure this is a valid issue.

**Comment by jerizm** [comment]
I'm guessing you have an admin URL specified like this.
```
    - name: kong-admin-url
      attributes:
        upstream_url: http://127.0.0.1:8001
        request_path: /kong
        strip_request_path: true
```

1. preserve_host is probably false so it returns `kong` as the hostname instead of the hostname you requested with.
2. The path needs to be stripped so `/kong/plugins` will map to `/plugins` but kong's admin api doesn't know that this stripped path needs to be appended to the next uri.

One way to work around these issues would be to add a dedicated hostname for kong admin configured like this. This way kong will respond with the configured hostname in the `next` uri.

```
- name: kong-admin-url
      ensure: present
      attributes:
        upstream_url: http://127.0.0.1:8001
        request_host: my-kong-admin-url.com
        preserve_host: true 
```

You would probably want to add some auth to this.
