### ISSUE TITLE
setting the anonymous property on a plugin is not possible in a declarative way

### ISSUE THREAD

**Issue by mvanholsteijn** [mybuilder/kongfig#93]
I want to configure the property 'anonymous' on the jwt authentication plugin.  As this requires the uuid of the consumer and I cannot set the uuid of the consumer in the kongfig file, it is not possible to do this in a declarative style. 

The following desired configuration results in  {"config.anonymous":"the anonymous user must be empty or a valid uuid"}

```
consumers:
  - username: anonymous
    plugins:
      - name: request-termination
        attributes:
          config:
            status_code: 403

plugins:
  - name: jwt
    attributes:
      config:
        claims_to_verify: [ 'exp', 'nbf' ]
        anonymous: 'anonymous'
```

Specifying the custom_id does not help either and I cannot set the customer id.
