### ISSUE TITLE
Env Variable substitution in config.yml

### ISSUE THREAD

**Issue by mo-mughrabi** [mybuilder/kongfig#96]
Hello everyone, 

kongfig is very cool, saved us tons of time, thank you. Is there a way to use env variable substitution  from env variable in config.yml file?

**Comment by CyExy** [comment]
You can use the [JS](https://github.com/mybuilder/kongfig/blob/master/config.js.sample) config files to use env variables. If you like to have the config in YAML then you can import the config in js config file and change what you need and use the JS config with kongfig.

**Comment by kstromeiraos** [comment]
@CyExy could we avoid the use of JS config file and do ENV variable substitution directly on YAML file?

**Comment by mo-mughrabi** [comment]
+1 @kstromeiraos

**Comment by CyExy** [comment]
I can see how this would be useful. How would this look:

```yaml
apis:
  - name: test
    ensure: present
    attributes:
      upstream_url: 'http://%env(HOST)%'
      hosts:
          - '%env(HOST)%'
```
So `HOST=mockbin.com kongfig apply ...` would produce

```yaml
apis:
  - name: "mockbin"
    ensure: "present"
    attributes:
      upstream_url: 'http://mockbin.com'
      hosts:
          - 'mockbin.com'
```

**Comment by kstromeiraos** [comment]
Looks good. And what do you think about this?

```
apis:
  - name: test
    ensure: present
    attributes:
      upstream_url: http://$(HOST)
      hosts:
          - $(HOST)
```

This way it would be more similar to Compose variables substitution.
