### ISSUE TITLE
API rate limited with different configs for different cosumers

### ISSUE THREAD

**Issue by takearun** [mybuilder/kongfig#97]
Hi,

What should be the kongfig yml declaration, to rate limit an API for two different consumers? 
The below repetition of rate-limiting, only adds the latter consumer,

```
- name: rate-limiting
        ensure: "present"
        attributes:
          enabled: true
          consumer_id: 456fee89-b22d-4ad0-8b09-adeb8bae6b18
          config:
            second: 5

- name: rate-limiting
        ensure: "present"
        attributes:
          enabled: true
          consumer_id: 322598c0-e51a-4239-8815-9f2e21f265d6
          config:
            second: 10
```

Appreciate your help.

Thanks,
Arun
